name: ZAP 

env:
  URI: http://bpcalapp-dev.eu-west-1.elasticbeanstalk.com         
  
on:
  push:
    branches:
    - master
  #workflow_dispatch:                  # manually triggered

jobs:

  zap_baseline_scan:

    runs-on: ubuntu-latest

    steps:

    - name: Pull Docker image for ZAP
      run: docker pull owasp/zap2docker-weekly

    - name: Run baseline scan
      run: docker run -v /report:/zap/wrk/:rw --user root -t owasp/zap2docker-weekly zap-baseline.py -t ${{env.URI}} -I -r zapreport.html
  
    - uses: actions/upload-artifact@v2
      name: upload ZAP report
      with:
        name: ZAPreport
        path: /report/zapreport.html
